version: "3.5"

services:

  mongo:
    image: mongo:5.0.7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: training
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"

  core:
    build: ../core
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: "${MONGODB_USERNAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"

  postgres:
    image: postgres:14.2-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  edge:
    build: ../edge
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_MAIL_PASSWORD: "${SPRING_MAIL_PASSWORD}"
      SPRING_MAIL_USERNAME: "${SPRING_MAIL_USERNAME}"